In [18]:
import pandas as pd

In [19]:
# remove b' from tweet text which has been a result of encoding wirrwarr
df_tweets_all = pd.read_csv('data/full_tweets_geo.csv')
df_tweets_all

,tweet_id,coordinates,place_full_name,place_country_code,place_bb_coord,created_at,text
0,848337741813358592,NaN,NaN,NaN,NaN,2017-04-02 00:54:13,b'fucks sake go away stupid anon \xe2\x80\x94 ...
1,850344984742174720,NaN,NaN,NaN,NaN,2017-04-07 13:50:17,b'Carlos Correa had gyalchester as his walkup ...
2,848668638869671939,NaN,NaN,NaN,NaN,2017-04-02 22:49:05,b'Damn dean just put Corbin to sleep. That Mat...
3,848338236770582529,NaN,NaN,NaN,NaN,2017-04-02 00:56:11,b'Dick Tracy Meets Gruesome - the 2017 re-boot...
4,847542736651767809,NaN,NaN,NaN,NaN,2017-03-30 20:15:09,b'what idiot called them antacids and not afte...
...,...,...,...,...,...,...,...
54275,849353459669372929,NaN,NaN,NaN,NaN,2017-04-04 20:10:19,b'RT @elijahdaniel: our comments section is a ...
54276,849004845877145604,NaN,NaN,NaN,NaN,2017-04-03 21:05:03,b'OH MY GOD LIZ JUST FUCKING BLOCKED ME IM SCR...
54277,850750334829854720,NaN,NaN,NaN,NaN,2017-04-08 16:41:00,b'RT @SilkyRay: Nigga had me fucked up https:/...
54278,849515175254405120,NaN,NaN,NaN,NaN,2017-04-05 06:52:55,"b""Swear to god it's the worst shit ever https:..."
54279,848891436112203776,NaN,NaN,NaN,NaN,2017-04-03 13:34:24,b'@FloydMayweather McGregor is going to rotate...

The tweet text is encoded in utf-8, python therefore places the letter 'b' in front of the string. This needs to be removed!

In [20]:
df_tweets_all['text'] = df_tweets_all['text'].str.slice(start=2, stop=-1)
df_tweets_all.to_csv('data/full_tweets_decoded.csv', encoding='utf-8')

In [21]:
df_tweets_decoded = pd.read_csv('data/full_tweets_decoded.csv')
df_tweets_decoded

,Unnamed: 0,tweet_id,coordinates,place_full_name,place_country_code,place_bb_coord,created_at,text
0,0,848337741813358592,NaN,NaN,NaN,NaN,2017-04-02 00:54:13,fucks sake go away stupid anon \xe2\x80\x94 ^ ...
1,1,850344984742174720,NaN,NaN,NaN,NaN,2017-04-07 13:50:17,Carlos Correa had gyalchester as his walkup mu...
2,2,848668638869671939,NaN,NaN,NaN,NaN,2017-04-02 22:49:05,Damn dean just put Corbin to sleep. That Match...
3,3,848338236770582529,NaN,NaN,NaN,NaN,2017-04-02 00:56:11,Dick Tracy Meets Gruesome - the 2017 re-boot\n...
4,4,847542736651767809,NaN,NaN,NaN,NaN,2017-03-30 20:15:09,what idiot called them antacids and not afterb...
...,...,...,...,...,...,...,...,...
54275,54275,849353459669372929,NaN,NaN,NaN,NaN,2017-04-04 20:10:19,RT @elijahdaniel: our comments section is a fu...
54276,54276,849004845877145604,NaN,NaN,NaN,NaN,2017-04-03 21:05:03,OH MY GOD LIZ JUST FUCKING BLOCKED ME IM SCREA...
54277,54277,850750334829854720,NaN,NaN,NaN,NaN,2017-04-08 16:41:00,RT @SilkyRay: Nigga had me fucked up https://t...
54278,54278,849515175254405120,NaN,NaN,NaN,NaN,2017-04-05 06:52:55,Swear to god it's the worst shit ever https://...
54279,54279,848891436112203776,NaN,NaN,NaN,NaN,2017-04-03 13:34:24,@FloydMayweather McGregor is going to rotate y...